bingo/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('bingo.views',
    url(r'^create$', 'create_game', name='create_game'),
    url(r'^claim/(?P<game_id>[\w-]+)/(?P<claim_type>[\w-]+)', 'claim', name='claim'),
    url(r'^clicked-number/(?P<game_id>[\w-]+)/(?P<number>\d+)', 'clicked_number', name='clicked_number'),
    url(r'create-ticket/(?P<game_id>[\w-]+)', 'create_ticket', name='create_ticket'),
	url(r'^(?P<game_id>[\w-]+)', 'game', name='game'),
    url(r'', 'game_list', name='game_list'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
    url('^auth/', include('users.urls')),
    # url('^one/', include('one.urls')),
    url('^game/', include('bingo.urls')),
    url('', include('tweets.urls')),
)

if settings.DEBUG:
    urlpatterns += patterns('django.views.static',
        (r'^media/(?P<path>.*)$', 'serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

bingo/models.py
from django.db import models

# Create your models here.

bingo/forms.py
from django import forms

class CreateGameForm(forms.Form):
    start_time = forms.CharField(max_length=40, required=True)
    finishing_time = forms.CharField(max_length=40, required=True)
    announcement_duration = forms.IntegerField(required=True)

bingo/views.py
import uuid
import json

from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from library.decorator import login_required
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib import messages

from bingo.forms import CreateGameForm
from library.bingo_scripts import ticket_html_generator

from datetime import timedelta
from datetime import datetime

import cass

@login_required
def clicked_number(request, game_id, number):

    success = 0
    user = request.session['username']
    if game_id not in request.session:
        request.session[game_id] = { }

    game_dict = request.session[game_id]
    if user not in game_dict:
        game_dict[user] = {
            'checked': [],
            'ticket': [],
            'announcement': [],
        }

    user_dict = game_dict[user]
    to_check_set = set(user_dict['ticket']).intersection(set(user_dict['announcement']))
    number = int(number)
    if number in to_check_set:
        user_dict['checked'].append(number)
        success = 1

    game_dict[user] = user_dict
    request.session[game_id] = game_dict
    if success:
        return HttpResponse("success")
    else:
        return HttpResponse(str(game_dict))



def game_list(request):
    """Shows list of games available"""

    games = cass.get_all_games()
    context = {
        'games': games,
    }
    return render_to_response(
        'bingo/games.html', context, context_instance=RequestContext(request))

@login_required
def game(request, game_id):

    user = request.session['username']
    if game_id not in request.session:
        request.session[game_id] = { }

    game_dict = request.session[game_id]
    if user not in game_dict:
        game_dict[user] = {
            'checked': [],
            'ticket': [],
            'announcement': [],
        }

    user_dict = game_dict[user]
    try:
        game_uuid = uuid.UUID(game_id)
        game = cass.get_game_details(game_uuid)
        announcement, announcement_time = cass.get_announcement(game_uuid)
        user_dict['announcement'] = announcement

    except Exception:
        context = {
            'error': "No Game Found",
            'game_id': game_id,
        }
    else:
        data = {
            'user': user,
            'game_id': game_uuid,
        }
        if not user_dict['ticket']:
            ticket = cass.get_ticket(**data)
            user_dict['ticket'] = list(ticket)
        else:
            ticket = user_dict['ticket']
        ticket_table = ticket_html_generator(ticket, user_dict)
        announcement_list = ", ".join(str(i) for i in announcement[1:])

        refresh_time = None
        if len(announcement) < 99:
            if announcement_time:
                next_announcement = announcement_time + timedelta(seconds=game.announcement_duration)
            else:
                next_announcement = game.start_time
            cur_time = datetime.now()
            print next_announcement, cur_time
            if next_announcement > cur_time:
                refresh_time = next_announcement - cur_time
                refresh_time = refresh_time.seconds * 1000
            if not refresh_time:
                refresh_time = game.announcement_duration * 1000

        context = {
            'message': messages.get_messages(request),
            'ticket': ticket_table,
            'game': game,
            'announcement': announcement_list if announcement_list else "None",
            'last_announcement': announcement[0] if announcement else "None",
            'game_id': game_id,
            'refresh_time': refresh_time,
        }

    game_dict[user] = user_dict
    request.session[game_id] = game_dict
    return render_to_response(
        'bingo/game.html',
        context,
        context_instance=RequestContext(request))

@login_required
def claim(request, game_id, claim_type):

    claims = {
        "four_corners": None,
        "top_row": None,
        "middle_row": None,
        "bottom_row": None,
        "full_house": None
    }
    user = request.session['username']
    try:
        game_uuid = uuid.UUID(game_id)
        game = cass.get_game_details(game_uuid)
        announcement, _ = cass.get_announcement(game_uuid)
        announcement = set(announcement)
        ticket = cass.get_ticket(game_uuid, user)
        ticket = [i for i in ticket if i]


    except Exception:
        pass
    else:
        claims['four_corners'] = game.four_corners
        claims['top_row'] = game.top_row
        claims['middle_row'] = game.middle_row
        claims['bottom_row'] = game.bottom_row
        claims['full_house'] = game.full_house
        claim_types = {'four_corners', 'top_row',
                'middle_row', 'bottom_row', 'full_house'}

        if ticket and claim_type == 'four_corners' and not claims.get(claim_type):
            corners = set([ticket[0], ticket[4], ticket[10], ticket[14]])
            if not corners - announcement:
                if cass.update_claim(game_uuid, user, claim_type):
                    claims[claim_type] = user
        elif ticket and claim_type == 'top_row' and not claims.get(claim_type):
            if not set(ticket[:5]) - announcement:
                if cass.update_claim(game_uuid, user, claim_type):
                    claims[claim_type] = user
        elif ticket and claim_type == 'middle_row' and not claims.get(claim_type):
            if not set(ticket[5:10]) - announcement:
                if cass.update_claim(game_uuid, user, claim_type):
                    claims[claim_type] = user
        elif ticket and claim_type == 'bottom_row' and not claims.get(claim_type):
            if not set(ticket[10:]) - announcement:
                if cass.update_claim(game_uuid, user, claim_type):
                    claims[claim_type] = user
        elif ticket and claim_type == 'full_house' and not claims.get(claim_type):
            if not set(ticket) - announcement:
                if cass.update_claim(game_uuid, user, claim_type):
                    claims[claim_type] = user


    return HttpResponse(json.dumps(claims),
                        content_type="application/json")


@login_required
def create_game(request):

    form = CreateGameForm(request.POST or None)
    if form.is_valid():
        game_id = uuid.uuid4()
        no_of_players = 0
        data = {
            'created_by': request.session['username'],
            'game_id': game_id,
            'start_time': form.cleaned_data['start_time'],
            'announcement_duration': form.cleaned_data['announcement_duration'],
            'end_time': form.cleaned_data['finishing_time'],
            'no_of_players': no_of_players,
        }
        cass.create_game(**data)
        return HttpResponseRedirect(reverse('game_list'))
    context = {
        'form': form,
        'request': request.POST,
    }
    return render_to_response(
        'bingo/create_game.html', context, context_instance=RequestContext(request))



@login_required
def create_ticket(request, game_id):

    try:
        game_id = uuid.UUID(game_id)
    except Exception:
        return HttpResponseRedirect(reverse('game', kwargs={'game_id': game_id}))
    user = request.session['username']
    data = {
        'user': user,
        'game_id': game_id,
    }
    ticket = cass.get_ticket(**data)
    if ticket:
        messages.add_message(request, messages.INFO, "Ticket Already exists.")
    else:
        ticket = cass.create_ticket(**data)
    return HttpResponseRedirect(reverse('game', kwargs={'game_id': game_id}))

templates/bingo/create_game.html
{% extends "base.html" %}

{% block title %}Create Game{% endblock %}

{% block head %}

<script>
    $( document ).ready(function() {
        $('#datetimepicker2').datetimepicker();



        $('body').on('focusout', $('.finish-time-cal'), function() {
            var start_time = $('.start_time').val().trim();
            var anouncement_time =  $('#id_announcement_duration').val().trim();
            if (start_time && anouncement_time && $.isNumeric(anouncement_time)){
                var timeObject = new Date(start_time);
                anouncement_time = parseInt(anouncement_time) * 99 * 1000;
                timeObject = new Date(timeObject.getTime() + anouncement_time);

                if ((timeObject.getMonth()+1).toString().length == 1) {
                    month = "0" + (timeObject.getMonth()+1);
                } else {
                    month = timeObject.getMonth()+1;
                }
                if (timeObject.getDate().toString().length == 1) {
                    ddate = "0" + timeObject.getDate();
                } else {
                    ddate = timeObject.getDate();
                }
                if ((timeObject.getHours()) > 12) {
                    hours = timeObject.getHours() - 12;
                    meridiem = "PM"
                } else if ((timeObject.getHours()) == 0) {
                    hours = 12;
                    meridiem = "AM"
                } else if ((timeObject.getHours()) == 12) {
                    hours = 12;
                    meridiem = "PM"
                } else {
                    hours = timeObject.getHours();
                    meridiem = "AM"
                }

                var dt = month + "/" + ddate + "/" + timeObject.getFullYear() + " " + hours +":" + timeObject.getMinutes() + ":" + timeObject.getSeconds() + " " + meridiem;
                $('#id_finishing_time').val(dt);

            }
            else if (anouncement_time && !$.isNumeric(anouncement_time)) {
                alert ("Anouncement time should be numeric");
            }
                
        });


    });

</script>
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-4 col-xs-6">
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="datetimepicker2">Time to Start the Game</label>
            <input type="text" class="form-control finish-time-cal start_time" name="start_time" id="datetimepicker2" />
          </div>
          <div class="form-group">
            <label for="id_announcement_duration">Number's Announcement Duration (in sec)</label>
            <input type="text" class="form-control finish-time-cal" name="announcement_duration" id="id_announcement_duration" placeholder="5" />
          </div>
          <div class="form-group">
            <label for="id_finishing_time">Game Finishing Time (at max)</label>
            <input type="text" class="form-control" name="finishing_time" id="id_finishing_time" readonly />
          </div>
          <input type="submit" class="btn btn-default" value="Create Game" />
        </form>
    </div>


</div>
{% endblock %}

templates/bingo/game.html
{% extends 'base.html' %}


{% block title %}Game - {{game_id}}{% endblock %}


{% block head %}
<script>
$( document ).ready(function() {
  $('.unchecked-number').on('click', function() {
    var current_item = this
    var number = $(current_item).html();
    var url = '/game/clicked-number/{{game_id}}/' + number;
    
    $.ajax({ 
        url: url
    }).done(function(data) {
      if (data == "success") {
        $(current_item).removeClass('unchecked-number');
        $(current_item).addClass('checked-number');
      }
    });
  });


  $('.claim_it').on('click', function() {
    var current_item = this
    var claim_type = this.id;
    var url = '/game/claim/{{game_id}}/' + claim_type;
    $.ajax({ 
        url: url
    }).done(function(data) {
      if (data[claim_type].trim().length > 0) { 
        $("."+claim_type).html(data[claim_type]);
      }
    });
        
  });
});
</script>
{% endblock %}



{% block body %}

  {% if refresh_time %}
    <body onload="setInterval('window.location.reload()', {{refresh_time}});">
  {% else %}
    <body>
  {% endif %}

{% endblock %}



{% block content %}

  {% if error %}
    <div class="col-md-12">
      <div class="alert alert-danger" role="alert">{{error}}</div>
    </div>
  {% else %}

    <div class="col-md-12">
      {% if message %}
        <div class="alert alert-info" role="alert">{{message}}</div>
      {% endif %}
      <table class="table table-striped table-hover dt-frame">
        <tbody>
          <tr>
            <th>Game ID</th>
            <td>{{game.game_id}}</td>
          </tr>
          <tr>
            <th>Start Time</th>
            <td>{{game.start_time}}</td>
          </tr>
          <tr>
            <th>End Time</th>
            <td>{{game.end_time}}</td>
          </tr>
          <tr>
            <th>Duration (in sec)</th>
            <td>{{game.announcement_duration}}</td>
          </tr>
          <tr>
            <th>Nunber of Players</th>
            <td>{{game.no_of_players}}</td>
          </tr>
          <tr>
            <th>Created By</th>
            <td>{{game.created_by}}</td>
          </tr>
          <tr>
            <th>Four corners</th>
            <td class="four_corners">
                {% if game.four_corners %}
                  {{game.four_corners}}
                {% else %}
                  <button class="btn btn-default btn-xs claim_it" id="four_corners">Claim it</a>
                {% endif %}
            </td>
          </tr>
          <tr>
            <th>Top Row</th>
            <td class="top_row">
                {% if game.top_row %}
                  {{game.top_row}}
                {% else %}
                  <button class="btn btn-default btn-xs claim_it" id="top_row">Claim it</a>
                {% endif %}
            </td>
          </tr>
          <tr>
            <th>Middle Row</th>
            <td class="middle_row">
                {% if game.middle_row %}
                  {{game.middle_row}}
                {% else %}
                  <button class="btn btn-default btn-xs claim_it" id="middle_row">Claim it</a>
                {% endif %}
            </td>
          </tr>
          <tr>
            <th>Bottom Row</th>
            <td class="bottom_row">
                {% if game.bottom_row %}
                  {{game.bottom_row}}
                {% else %}
                  <button class="btn btn-default btn-xs claim_it" id="bottom_row">Claim it</a>
                {% endif %}
            </td>
          </tr>
          <tr>
            <th>Full House</th>
            <td class="full_house">
                {% if game.full_house %}
                  {{game.full_house}}
                {% else %}
                  <button class="btn btn-default btn-xs claim_it" id="full_house">Claim it</a>
                {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-12">
      {% if not ticket %}
        <center><a href="{% url 'create_ticket' game_id %}" class="btn btn-primary" >Generate Your Ticket</a></center><br/>
      {% else %}
        <div class="panel panel-primary">
          <div class="panel-heading">Your Ticket</div>
          <table class="table">
            {{ticket|safe}}
          </table>
        </div>
      {% endif %}
    </div>

    <div class="col-md-8 col-sm-8">
      <div class="panel panel-primary">
        <div class="panel-heading">Numbers already announced</div>
        <div class="panel-body">{{announcement}}</div>
      </div>
    </div>
    <div class="col-md-4 col-sm-4">
      <div class="panel panel-primary">
        <div class="panel-heading">Last Numbers announced</div>
        <div class="panel-body">
          <center><h1>{{last_announcement}}</h1></center>
        </div>
      </div>
    </div>

  {% endif %}
{% endblock %}

templates/bingo/games.html
{% extends 'base.html' %}


{% block title %}Game - List{% endblock %}

{% block head %}
    <script>
        $(document).ready(function(){
            $('.dt-frame').DataTable({
                "order": [[ 1, "asc" ],[ 2, "desc" ]],
                "lengthMenu": [[15, 25, 50, -1], [15, 25, 50, "All"]]
            });
        });
    </script>
{% endblock %}

{% block content %}

  <center><a href="{% url 'create_game' %}" class="btn btn-default" >Create New Game</a></center>
  <table class="table table-striped table-hover dt-frame">
    <thead>
      <tr>
        <th>Game ID</th>
        <th>Start Time</th>
        <th>Duration (in sec)</th>
      </tr>
    </thead>
    <tbody>
      {% for record in games %}
        <tr {% if record.is_active == False %} class="danger" 
            {% endif %}>
          <td>
              <a href="{% url 'game' record.game_id %}">
                  {{record.game_id}}
              </a>
          </td>
          <td>{{record.start_time}}</td>
          <td>{{record.announcement_duration}}</td>
        </tr>
      {% endfor %}
    </tbody>
</table>
{% endblock %}